"""Built-in contextualizer provider names and defaults."""

from __future__ import annotations

NOOP_CONTEXTUALIZER_ID = "noop"
CONTEXTUALIZER_DISABLED_ALIAS = "none"
ANTHROPIC_CONTEXTUALIZER_ID = "anthropic"
DEFAULT_ANTHROPIC_CONTEXTUALIZER_MODEL = "claude-haiku-4-5-20251001"
CONTEXTUALIZER_PROVIDER_ORDER = (
    NOOP_CONTEXTUALIZER_ID,
    ANTHROPIC_CONTEXTUALIZER_ID,
)

__all__ = [
    "ANTHROPIC_CONTEXTUALIZER_ID",
    "CONTEXTUALIZER_DISABLED_ALIAS",
    "CONTEXTUALIZER_PROVIDER_ORDER",
    "DEFAULT_ANTHROPIC_CONTEXTUALIZER_MODEL",
    "NOOP_CONTEXTUALIZER_ID",
]
