"""Tool contracts and scope helpers for app-owned retrieval integrations."""

from .tool_contracts import (
    SEARCH_USER_DOCUMENTS_INPUT_SCHEMA,
    SEARCH_USER_DOCUMENTS_DEFAULT_LIMIT,
    SEARCH_USER_DOCUMENTS_DEFAULT_MAX_CHARS,
    SEARCH_USER_DOCUMENTS_DEFAULT_RERANK,
    SEARCH_USER_DOCUMENTS_DEFAULT_USE_LEXICAL_SEARCH,
    SEARCH_USER_DOCUMENTS_LIMIT_MAX,
    SEARCH_USER_DOCUMENTS_LIMIT_MIN,
    SEARCH_USER_DOCUMENTS_MAX_CHARS_MAX,
    SEARCH_USER_DOCUMENTS_MAX_CHARS_MIN,
    SEARCH_USER_DOCUMENTS_MAX_TOKENS_MAX,
    SEARCH_USER_DOCUMENTS_MAX_TOKENS_MIN,
    SEARCH_USER_DOCUMENTS_OUTPUT_SCHEMA,
    SEARCH_USER_DOCUMENTS_TOOL_NAME,
    SearchUserDocumentsRequest,
    SupportsContextPromptPayload,
    SupportsContextPackPromptPayload,
    ToolContract,
    normalize_static_content_types,
    normalize_static_retrieval_scope,
    parse_search_user_documents_request,
    scope_document_ids,
    search_user_documents_tool_contract,
    search_user_documents_tool_result,
    validate_bound_namespace,
    validate_search_user_documents_bounds,
)

__all__ = (
    "SEARCH_USER_DOCUMENTS_INPUT_SCHEMA",
    "SEARCH_USER_DOCUMENTS_DEFAULT_LIMIT",
    "SEARCH_USER_DOCUMENTS_DEFAULT_MAX_CHARS",
    "SEARCH_USER_DOCUMENTS_DEFAULT_RERANK",
    "SEARCH_USER_DOCUMENTS_DEFAULT_USE_LEXICAL_SEARCH",
    "SEARCH_USER_DOCUMENTS_LIMIT_MAX",
    "SEARCH_USER_DOCUMENTS_LIMIT_MIN",
    "SEARCH_USER_DOCUMENTS_MAX_CHARS_MAX",
    "SEARCH_USER_DOCUMENTS_MAX_CHARS_MIN",
    "SEARCH_USER_DOCUMENTS_MAX_TOKENS_MAX",
    "SEARCH_USER_DOCUMENTS_MAX_TOKENS_MIN",
    "SEARCH_USER_DOCUMENTS_OUTPUT_SCHEMA",
    "SEARCH_USER_DOCUMENTS_TOOL_NAME",
    "SearchUserDocumentsRequest",
    "SupportsContextPromptPayload",
    "SupportsContextPackPromptPayload",
    "ToolContract",
    "normalize_static_content_types",
    "normalize_static_retrieval_scope",
    "parse_search_user_documents_request",
    "scope_document_ids",
    "search_user_documents_tool_contract",
    "search_user_documents_tool_result",
    "validate_bound_namespace",
    "validate_search_user_documents_bounds",
)
