"""Document-format support matrix."""

from __future__ import annotations

from .format_support_lookup import (
    extensions_for_converter,
    mime_types_for_converter,
)
from .format_support_models import FormatSupport


FORMAT_SUPPORT_MATRIX: tuple[FormatSupport, ...] = (
    FormatSupport(
        key="text",
        label="Text and markdown",
        support_level="first_party_stable",
        converter_key="text",
        extensions=extensions_for_converter("text"),
        mime_types=mime_types_for_converter("text"),
        local_ingest=True,
        ocr="none",
        notes="Plain text, markdown, YAML, TOML, logs, config, and similar text files.",
    ),
    FormatSupport(
        key="code",
        label="Source code",
        support_level="first_party_stable",
        converter_key="code",
        extensions=extensions_for_converter("code"),
        mime_types=mime_types_for_converter("code"),
        local_ingest=True,
        ocr="none",
        notes="Text source files with language metadata for downstream chunking.",
    ),
    FormatSupport(
        key="html",
        label="HTML",
        support_level="first_party_stable",
        converter_key="html",
        extensions=extensions_for_converter("html"),
        mime_types=mime_types_for_converter("html"),
        local_ingest=True,
        ocr="none",
        notes="Local HTML extraction with markdown fallbacks; browser rendering is not part of this path.",
    ),
    FormatSupport(
        key="csv",
        label="CSV and TSV",
        support_level="first_party_stable",
        converter_key="csv",
        extensions=extensions_for_converter("csv"),
        mime_types=mime_types_for_converter("csv"),
        local_ingest=True,
        ocr="none",
        notes="Delimiter detection and markdown-table rendering.",
    ),
    FormatSupport(
        key="json",
        label="JSON and JSONL",
        support_level="first_party_stable",
        converter_key="json",
        extensions=extensions_for_converter("json"),
        mime_types=mime_types_for_converter("json"),
        local_ingest=True,
        ocr="none",
        notes="Pretty-printed structured text for indexing.",
    ),
    FormatSupport(
        key="xml",
        label="XML",
        support_level="first_party_stable",
        converter_key="xml",
        extensions=extensions_for_converter("xml"),
        mime_types=mime_types_for_converter("xml"),
        local_ingest=True,
        ocr="none",
        notes="Defused XML parsing with safe text fallback.",
    ),
    FormatSupport(
        key="pdf",
        label="PDF",
        support_level="first_party_beta",
        converter_key="pdf",
        extensions=extensions_for_converter("pdf"),
        mime_types=mime_types_for_converter("pdf"),
        local_ingest=True,
        ocr="optional_pages",
        notes="PDF Inspector when available, PyMuPDF fallback, and partial OCR routing signals.",
    ),
    FormatSupport(
        key="docx",
        label="DOCX",
        support_level="first_party_beta",
        converter_key="docx",
        extensions=extensions_for_converter("docx"),
        mime_types=mime_types_for_converter("docx"),
        local_ingest=True,
        ocr="quality_fallback",
        notes="OOXML DOCX only; .doc is intentionally unsupported.",
    ),
    FormatSupport(
        key="pptx",
        label="PPTX",
        support_level="first_party_beta",
        converter_key="pptx",
        extensions=extensions_for_converter("pptx"),
        mime_types=mime_types_for_converter("pptx"),
        local_ingest=True,
        ocr="quality_fallback",
        notes="OOXML PPTX only; .ppt is intentionally unsupported.",
    ),
    FormatSupport(
        key="xlsx",
        label="XLSX",
        support_level="first_party_beta",
        converter_key="xlsx",
        extensions=extensions_for_converter("xlsx"),
        mime_types=mime_types_for_converter("xlsx"),
        local_ingest=True,
        ocr="none",
        notes="OOXML XLSX only; .xls is intentionally unsupported.",
    ),
    FormatSupport(
        key="image",
        label="Images",
        support_level="first_party_beta",
        converter_key="image",
        extensions=extensions_for_converter("image"),
        mime_types=mime_types_for_converter("image"),
        local_ingest=False,
        ocr="required",
        notes="Images require an injected OCR provider; default local ingest excludes them.",
    ),
)
