"""Document-format support matrix."""

from __future__ import annotations

from .converter_keys import (
    CODE_CONVERTER_KEY,
    CSV_CONVERTER_KEY,
    DOCX_CONVERTER_KEY,
    HTML_CONVERTER_KEY,
    IMAGE_CONVERTER_KEY,
    JSON_CONVERTER_KEY,
    PDF_CONVERTER_KEY,
    PPTX_CONVERTER_KEY,
    TEXT_CONVERTER_KEY,
    XLSX_CONVERTER_KEY,
    XML_CONVERTER_KEY,
)
from .format_support_lookup import (
    extensions_for_converter,
    mime_types_for_converter,
)
from .format_support_models import FormatSupport


FORMAT_SUPPORT_MATRIX: tuple[FormatSupport, ...] = (
    FormatSupport(
        key=TEXT_CONVERTER_KEY,
        label="Text and markdown",
        maturity="stable",
        converter_key=TEXT_CONVERTER_KEY,
        extensions=extensions_for_converter(TEXT_CONVERTER_KEY),
        mime_types=mime_types_for_converter(TEXT_CONVERTER_KEY),
        local_ingest=True,
        ocr="none",
        notes="Plain text, markdown, YAML, TOML, logs, config, and similar text files.",
    ),
    FormatSupport(
        key=CODE_CONVERTER_KEY,
        label="Source code",
        maturity="stable",
        converter_key=CODE_CONVERTER_KEY,
        extensions=extensions_for_converter(CODE_CONVERTER_KEY),
        mime_types=mime_types_for_converter(CODE_CONVERTER_KEY),
        local_ingest=True,
        ocr="none",
        notes="Text source files with language metadata for downstream chunking.",
    ),
    FormatSupport(
        key=HTML_CONVERTER_KEY,
        label="HTML",
        maturity="stable",
        converter_key=HTML_CONVERTER_KEY,
        extensions=extensions_for_converter(HTML_CONVERTER_KEY),
        mime_types=mime_types_for_converter(HTML_CONVERTER_KEY),
        local_ingest=True,
        ocr="none",
        notes="Local HTML extraction with markdown fallbacks; browser rendering is not part of this path.",
    ),
    FormatSupport(
        key=CSV_CONVERTER_KEY,
        label="CSV and TSV",
        maturity="stable",
        converter_key=CSV_CONVERTER_KEY,
        extensions=extensions_for_converter(CSV_CONVERTER_KEY),
        mime_types=mime_types_for_converter(CSV_CONVERTER_KEY),
        local_ingest=True,
        ocr="none",
        notes="Delimiter detection and markdown-table rendering.",
    ),
    FormatSupport(
        key=JSON_CONVERTER_KEY,
        label="JSON and JSONL",
        maturity="stable",
        converter_key=JSON_CONVERTER_KEY,
        extensions=extensions_for_converter(JSON_CONVERTER_KEY),
        mime_types=mime_types_for_converter(JSON_CONVERTER_KEY),
        local_ingest=True,
        ocr="none",
        notes="Pretty-printed structured text for indexing.",
    ),
    FormatSupport(
        key=XML_CONVERTER_KEY,
        label="XML",
        maturity="stable",
        converter_key=XML_CONVERTER_KEY,
        extensions=extensions_for_converter(XML_CONVERTER_KEY),
        mime_types=mime_types_for_converter(XML_CONVERTER_KEY),
        local_ingest=True,
        ocr="none",
        notes="Defused XML parsing with safe text fallback.",
    ),
    FormatSupport(
        key=PDF_CONVERTER_KEY,
        label="PDF",
        maturity="beta",
        converter_key=PDF_CONVERTER_KEY,
        extensions=extensions_for_converter(PDF_CONVERTER_KEY),
        mime_types=mime_types_for_converter(PDF_CONVERTER_KEY),
        local_ingest=True,
        ocr="optional_pages",
        notes="PDF Inspector when available, PyMuPDF fallback, and partial OCR routing signals.",
    ),
    FormatSupport(
        key=DOCX_CONVERTER_KEY,
        label="DOCX",
        maturity="beta",
        converter_key=DOCX_CONVERTER_KEY,
        extensions=extensions_for_converter(DOCX_CONVERTER_KEY),
        mime_types=mime_types_for_converter(DOCX_CONVERTER_KEY),
        local_ingest=True,
        ocr="quality_fallback",
        notes="OOXML DOCX only; .doc is intentionally unsupported.",
    ),
    FormatSupport(
        key=PPTX_CONVERTER_KEY,
        label="PPTX",
        maturity="beta",
        converter_key=PPTX_CONVERTER_KEY,
        extensions=extensions_for_converter(PPTX_CONVERTER_KEY),
        mime_types=mime_types_for_converter(PPTX_CONVERTER_KEY),
        local_ingest=True,
        ocr="quality_fallback",
        notes="OOXML PPTX only; .ppt is intentionally unsupported.",
    ),
    FormatSupport(
        key=XLSX_CONVERTER_KEY,
        label="XLSX",
        maturity="beta",
        converter_key=XLSX_CONVERTER_KEY,
        extensions=extensions_for_converter(XLSX_CONVERTER_KEY),
        mime_types=mime_types_for_converter(XLSX_CONVERTER_KEY),
        local_ingest=True,
        ocr="none",
        notes="OOXML XLSX only; .xls is intentionally unsupported.",
    ),
    FormatSupport(
        key=IMAGE_CONVERTER_KEY,
        label="Images",
        maturity="beta",
        converter_key=IMAGE_CONVERTER_KEY,
        extensions=extensions_for_converter(IMAGE_CONVERTER_KEY),
        mime_types=mime_types_for_converter(IMAGE_CONVERTER_KEY),
        local_ingest=False,
        ocr="required",
        notes="Images require an injected OCR provider; default local ingest excludes them.",
    ),
)
