from __future__ import annotations

import mimetypes
import os


mimetypes.add_type("application/x-ndjson", ".ndjson")

JSONL_MIME_TYPES = (
    "application/jsonl",
    "application/jsonlines",
    "application/ldjson",
    "application/x-ldjson",
)
NDJSON_MIME_TYPES = (
    "application/ndjson",
    "application/x-ndjson",
)


MIME_TYPE_MAP: dict[str, str] = {
    "application/pdf": "pdf",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "docx",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation": "pptx",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "xlsx",
    "text/html": "html",
    "application/xhtml+xml": "html",
    "text/csv": "csv",
    "text/tab-separated-values": "csv",
    "application/json": "json",
    **{mime_type: "json" for mime_type in JSONL_MIME_TYPES},
    **{mime_type: "json" for mime_type in NDJSON_MIME_TYPES},
    "application/xml": "xml",
    "text/xml": "xml",
    "text/plain": "text",
    "text/markdown": "text",
    "text/x-markdown": "text",
    "text/yaml": "text",
    "text/x-yaml": "text",
    "application/x-yaml": "text",
    "application/toml": "text",
    "image/jpeg": "image",
    "image/png": "image",
    "image/gif": "image",
    "image/webp": "image",
    "image/bmp": "image",
    "image/tiff": "image",
    "image/svg+xml": "text",
}

EXTENSION_MAP: dict[str, str] = {
    ".pdf": "pdf",
    ".docx": "docx",
    ".pptx": "pptx",
    ".xlsx": "xlsx",
    ".html": "html",
    ".htm": "html",
    ".csv": "csv",
    ".tsv": "csv",
    ".json": "json",
    ".jsonl": "json",
    ".ndjson": "json",
    ".xml": "xml",
    ".txt": "text",
    ".md": "text",
    ".markdown": "text",
    ".yaml": "text",
    ".yml": "text",
    ".toml": "text",
    ".rst": "text",
    ".adoc": "text",
    ".tex": "text",
    ".ini": "text",
    ".cfg": "text",
    ".conf": "text",
    ".env": "text",
    ".properties": "text",
    ".log": "text",
    ".py": "code",
    ".js": "code",
    ".ts": "code",
    ".tsx": "code",
    ".jsx": "code",
    ".java": "code",
    ".c": "code",
    ".cpp": "code",
    ".cc": "code",
    ".cxx": "code",
    ".h": "code",
    ".hpp": "code",
    ".m": "code",
    ".cs": "code",
    ".go": "code",
    ".rs": "code",
    ".rb": "code",
    ".php": "code",
    ".swift": "code",
    ".kt": "code",
    ".kts": "code",
    ".scala": "code",
    ".d": "code",
    ".jl": "code",
    ".ex": "code",
    ".exs": "code",
    ".erl": "code",
    ".clj": "code",
    ".groovy": "code",
    ".dart": "code",
    ".hs": "code",
    ".ml": "code",
    ".fs": "code",
    ".nim": "code",
    ".cr": "code",
    ".zig": "code",
    ".lua": "code",
    ".pl": "code",
    ".r": "code",
    ".sh": "code",
    ".bash": "code",
    ".zsh": "code",
    ".ps1": "code",
    ".bat": "code",
    ".cmd": "code",
    ".sql": "code",
    ".graphql": "code",
    ".gql": "code",
    ".proto": "code",
    ".tf": "code",
    ".tfvars": "code",
    ".hcl": "code",
    ".gradle": "code",
    ".cmake": "code",
    ".make": "code",
    ".mak": "code",
    ".css": "code",
    ".scss": "code",
    ".sass": "code",
    ".less": "code",
    ".vue": "code",
    ".svelte": "code",
    ".jpg": "image",
    ".jpeg": "image",
    ".png": "image",
    ".gif": "image",
    ".webp": "image",
    ".bmp": "image",
    ".tiff": "image",
    ".tif": "image",
}


def registered_converter_key(*, filename: str, mime_type: str) -> str | None:
    mt = (mime_type or "").strip().lower()
    _, ext = os.path.splitext((filename or "").lower())
    return MIME_TYPE_MAP.get(mt) or EXTENSION_MAP.get(ext)


def is_registered_image_document(*, filename: str, mime_type: str) -> bool:
    return registered_converter_key(filename=filename, mime_type=mime_type) == "image"
